### ISSUE TITLE
What is happening on this repo?

### ISSUE THREAD

**Issue by reitowo** [rizinorg/llvm-capstone#5]
It seems latest commit wiped out capstone code.

**Comment by kabeor** [comment]
@cnSchwarzer see [here](https://github.com/capstone-engine/capstone/pull/1949#issuecomment-1531733670)

**Comment by reitowo** [comment]
Thanks

**Comment by reitowo** [comment]
So when will the whole thing being merged? Does this repository already generates new code for capstone?

And, any migration guide for creating a new arch in TableGen and use this tool to generate capstone stuff?

**Comment by XVilka** [comment]
@cnSchwarzer see:
- https://github.com/capstone-engine/capstone/pull/1949#issuecomment-1537135354
- https://github.com/capstone-engine/capstone/pull/2013

**Comment by reitowo** [comment]
Thanks!
